
[functions.twilio-dispatcher]
enabled = true
verify_jwt = false
import_map = "./functions/twilio-dispatcher/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/twilio-dispatcher/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/twilio-dispatcher/*.html" ]

[functions.send-outbound-sms]
enabled = true
verify_jwt = false
import_map = "./functions/send-outbound-sms/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-outbound-sms/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-outbound-sms/*.html" ]

[functions.gemini-chat]
enabled = true
verify_jwt = false
import_map = "./functions/gemini-chat/deno.json"
entrypoint = "./functions/gemini-chat/index.ts"
